services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: no
    container_name: employeedb
    volumes:
      - "./scripts:/scripts"
    ports:
      - "1433:1433"
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=Ranmal@ousl1433"
 
